name: "github-write-file"
description: "Writes user input content onto user specified file"
inputs:
  path:
    description: "Path of file to write on"
    required: true
    default: ""
  content:
    description: "Content to write on file"
    required: true
    default: ""
outputs:
  content:
    description: "Content written to the file"
runs:
  using: "node16"
  main: "dist/index.js"
